{
 "title": "External secrets",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Synced secrets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(externalsecret_status_condition{condition=\"Ready\"})"
    }
   ]
  },
  {
   "title": "Sync errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(externalsecret_sync_calls_error)"
    }
   ]
  },
  {
   "title": "Secrets (ready)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "externalsecret_status_condition{condition=\"Ready\"}"
    }
   ]
  },
  {
   "title": "Secrets (deleted)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "externalsecret_status_condition{condition=\"Deleted\"}"
    }
   ]
  },
  {
   "title": "Sync calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(externalsecret_sync_calls_total[30m])"
    }
   ]
  }
 ]
}