{
 "title": "GitLab - Gitaly",
 "description": "GitLab Gitaly service metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"gitaly\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gitaly Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "topk(1, count by (version) (gitlab_build_info{job=\"gitaly\"}))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"gitaly\"}",
     "legendFormat": "Go routines {{instance}}"
    },
    {
     "expr": "process_open_fds{job=\"gitaly\"}",
     "legendFormat": "Open FDs"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(up{job=\"gitaly\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"gitaly\"}",
     "legendFormat": "RSS - {{instance}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"gitaly\"}",
     "legendFormat": "Next GC - {{instance}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum without (grpc_method,grpc_service,grpc_type) (\n  rate(grpc_server_started_total{job=\"gitaly\"}[$__interval])\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}