{
 "title": "GitLab Omnibus",
 "description": "GitLab Omnibus Dashboard (>= 10.3)",
 "tags": [ "GitLab" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Unicorn Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(up{job=\"gitlab-unicorn\"})"
    }
   ]
  },
  {
   "title": "Postgres Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(pg_up)" }
   ]
  },
  {
   "title": "Sidekiq Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(up{job=\"gitlab-sidekiq\"})"
    }
   ]
  },
  {
   "title": "Workhorse Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(up{job=\"gitlab-workhorse\"})"
    }
   ]
  },
  {
   "title": "Redis Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_up{instance=\"gitlab\",job=\"gitlab\"}"
    }
   ]
  },
  {
   "title": "Gitaly Up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(up{job=\"gitaly\"})"
    }
   ]
  },
  {
   "title": "Node DIsk Free",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_avail{fstype!~\"tmpfs\"}) / sum(node_filesystem_size{fstype!~\"tmpfs\"})"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes{fstype!~\"tmpfs\"}) / sum(node_filesystem_size_bytes{fstype!~\"tmpfs\"})"
    }
   ]
  },
  {
   "title": "Sidekiq Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(sidekiq_queue_size)", "legendFormat": "Jobs" }
   ]
  },
  {
   "title": "Workhorse Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.95, rate(gitlab_workhorse_request_duration_seconds_bucket[5m])))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(histogram_quantile(0.95, rate(gitlab_workhorse_request_duration_seconds_bucket[5m])))",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(histogram_quantile(0.95, rate(gitlab_workhorse_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(histogram_quantile(0.95, rate(gitlab_workhorse_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}