{
 "title": "MongoDB (Percona)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(mongodb_up, namespace)"
    }
   },
   {
    "name": "rs_name",
    "label": "Replicaset name",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_name, set){namespace=\"$namespace\"}"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Query Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{rs_nm=\"$rs_name\",namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Replica query operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{rs_nm=\"$rs_name\",namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{rs_nm=~\"$rs_name\",namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Database objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_mongod_db_objects_total{rs_nm=\"$rs_name\",namespace=\"$namespace\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Databases size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodb_mongod_db_data_size_bytes{rs_nm=\"$rs_name\",namespace=\"$namespace\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Databases's collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(mongodb_mongod_db_collections_total{rs_nm=~\"$rs_name\",namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Members state",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_rs_members_state{rs_nm=\"$rs_name\",namespace=\"$namespace\"}",
     "legendFormat": "{{member_idx}} ({{member_state}})"
    }
   ]
  },
  {
   "title": "Members health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{set=~\"$rs_name\"}",
     "legendFormat": "# members"
    },
    {
     "expr": "sum(mongodb_mongod_replset_number_of_members{set=~\"$rs_name\"})",
     "legendFormat": "healthy members"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_connections{rs_nm=\"$rs_name\",namespace=\"$namespace\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(max(mongodb_mongod_replset_member_optime_date{state=\"PRIMARY\", set=\"$rs_name\"}) - min(mongodb_mongod_replset_member_optime_date{state=\"SECONDARY\"} * on (name) group_left mongodb_mongod_replset_my_name{set=\"$rs_name\"})) or vector(0)",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_cursor_open{rs_nm=\"$rs_name\",namespace=\"$namespace\"} or mongodb_mongod_cursors{rs_nm=\"$rs_name\",namespace=\"$namespace\"} or mongodb_mongos_metrics_cursor_open{rs_nm=\"$rs_name\",namespace=\"$namespace\"} or mongodb_mongos_cursors{rs_nm=\"$rs_name\",namespace=\"$namespace\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{rs_nm=\"$rs_name\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_connections{rs_nm=~\"$rs_name\",namespace=\"$namespace\",state=\"current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_connections{rs_nm=~\"$rs_name\",namespace=\"$namespace\",state=\"available\"}",
     "legendFormat": "{{$rs_nm}}"
    }
   ]
  },
  {
   "title": "Oplog Buffer Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_size_bytes{rs_nm=\"$rs_name\",namespace=\"$namespace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "mongodb_mongod_metrics_repl_buffer_max_size_bytes{rs_nm=\"$rs_name\",namespace=\"$namespace\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Oplog size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongodb_oplog_stats_size{rs_nm=\"$rs_name\",namespace=\"$namespace\"}",
     "legendFormat": "{{rs_nm}}"
    }
   ]
  },
  {
   "title": "Oplog Buffered Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_repl_buffer_count{rs_nm=\"$rs_name\",namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{rs_nm}}"
    }
   ]
  },
  {
   "title": "Disk IO usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(rate(node_disk_io_time_seconds_total[$interval]) or irate(node_disk_io_time_seconds_total[$interval]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "expr": "mongodb_memory", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_network_metrics_num_requests_total{rs_nm=~\"$rs_name\",namespace=\"$namespace\"}[$interval])",
     "legendFormat": "{{rs_nm}}"
    }
   ]
  }
 ]
}