{
 "title": "Jenkins monitoring",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage, Jenkins Job Status, and lot more.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "filter_job" }
  ]
 },
 "panels": [
  { "title": "Jenkins jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processing speed",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "range",
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count[$__interval])"
    }
   ]
  },
  {
   "title": "10 Longest jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk (10,default_jenkins_builds_last_build_duration_milliseconds{jenkins_job=~\".*$filter_job.*\"})",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Queued rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "range",
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count[$__interval])"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(jenkins_runs_success_total[$__interval])) / sum(rate(jenkins_runs_total_total[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 8 },
   "format": "none",
   "valueName": "range",
   "targets": [
    { "expr": "jenkins_runs_total_total" }
   ]
  },
  {
   "title": "Sucessful Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "range",
   "targets": [
    { "expr": "jenkins_runs_success_total" }
   ]
  },
  {
   "title": "Aborted Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "range",
   "targets": [
    { "expr": "jenkins_runs_aborted_total" }
   ]
  },
  {
   "title": "Unstable Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_unstable_total" }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "range",
   "targets": [
    { "expr": "jenkins_runs_failure_total" }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_queue_size_value" }
   ]
  },
  { "title": "Jenkins executors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Executor free",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_free_value" }
   ]
  },
  {
   "title": "Executors working availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jenkins_executor_in_use_history{instance=\"jenkins-master\",job=\"jenkins\",quantile=\"0.999\"}"
    }
   ]
  },
  {
   "title": "Executor In-use",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_in_use_value" }
   ]
  },
  { "title": "Jenkins health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "JVM free memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vm_memory_total_max - vm_memory_total_used) / vm_memory_total_max * 100.0"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "vm_memory_total_used" }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_health_check_score" }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 21 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "vm_uptime_milliseconds" }
   ]
  },
  {
   "title": "Jenkins nodes offline",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_node_offline_value" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "vm_cpu_load" }
   ]
  }
 ]
}