{
 "title": "Java application overview",
 "description": "Java application for SpringBoot",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(jvm_classes_loaded_classes, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(jvm_classes_loaded_classes{namespace=~\"$namespace\"}, service)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of instances",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container=\"aon-com-api\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$service\", area=\"heap\", namespace=\"$namespace\"})*100/sum(jvm_memory_max_bytes{service=\"$service\", area=\"heap\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$service\", area=\"nonheap\", namespace=\"$namespace\"})*100/sum(jvm_memory_max_bytes{service=\"$service\", area=\"nonheap\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - sum(rate(logback_events_total{level=\"error\", service=\"$service\", namespace=\"$namespace\"}[2m])) / sum(rate(logback_events_total{service=\"$service\", namespace=\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "System CPU Usage {{pod }}"
    },
    {
     "expr": "process_cpu_usage{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Process CPU Usage {{ pod }}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Load Average [1m] {{pod}}"
    },
    {
     "expr": "system_cpu_count{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "CPU Core Size {{pod}}"
    }
   ]
  },
  {
   "title": "JVM heap usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (jvm_memory_used_bytes{service=\"$service\", area=\"heap\", namespace=\"$namespace\"})",
     "legendFormat": "JVM memory {{pod}}"
    },
    {
     "expr": "sum by (pod) (jvm_memory_max_bytes{service=\"$service\", area=\"heap\", namespace=\"$namespace\"})",
     "legendFormat": "Max JVM memory {{pod}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{service=\"$service\", uri!~\".*actuator.*\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{service=\"$service\", exception=\"None\", uri!~\".*actuator.*\", namespace=\"$namespace\"}[5m]) / irate(http_server_requests_seconds_count{service=\"$service\", exception=\"None\", uri!~\".*actuator.*\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  { "title": "Logback Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "INFO logs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{service=\"$service\", level=\"info\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "info {{pod}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{service=\"$service\", level=\"error\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "error {{pod}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{service=\"$service\", level=\"warn\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "warn {{pod}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DEBUG logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{service=\"$service\", level=\"debug\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "debug {{pod}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "TRACE logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{service=\"$service\", level=\"trace\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "trace {{pod}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}