{
 "title": "1. Kubernetes Workload",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics (741)",
 "tags": [
  "kubernetes",
  "deployment"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_daemonset_created, namespace)"
   },
   {
    "name": "Deployment",
    "query": "label_values(kube_deployment_created, deployment)"
   },
   {
    "name": "Statefulset",
    "query": "label_values(kube_statefulset_created, statefulset)"
   },
   {
    "name": "Daemonset",
    "query": "label_values(kube_daemonset_created, daemonset)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\",pod_name!=\"\", namespace=~\"$namespace\"}) / sum (kube_node_status_allocatable_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\", namespace=~\"$namespace\"}[2m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0))) - ((sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)))) / ((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0))) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\", pod_name!=\"\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\", namespace=~\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum (machine_cpu_cores)" }
   ]
  },
  {
   "title": "Available (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Total (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))",
     "legendFormat": "{{ $Daemonset }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",io_kubernetes_container_name!=\"POD\",pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\", namespace=~\"$namespace\"}[1m])) by (pod_name)",
     "legendFormat": "real: {{ pod_name }} "
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{pod=~\"^$Deployment$Statefulset$Daemonset.*$\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "rqst: {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\", namespace=~\"$namespace\"}) by (pod_name)",
     "legendFormat": "real: {{ pod_name }}"
    },
    {
     "expr": "sum ((kube_pod_container_resource_requests_memory_bytes{pod=~\"^$Deployment$Statefulset$Daemonset.*$\", namespace=~\"$namespace\"})) by (pod)",
     "legendFormat": "rqst: {{ pod }}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0))",
     "legendFormat": "available"
    },
    {
     "expr": "(((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0))) - ((sum(kube_deployment_status_replicas_available{deployment=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)))) / ((sum(kube_deployment_status_replicas{deployment=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Deployment$Statefulset$Daemonset\", namespace=~\"$namespace\"}) or vector(0)))",
     "legendFormat": "unavailable"
    },
    {
     "expr": "sum(kube_hpa_spec_max_replicas{hpa=~\".*$Deployment$Statefulset$Daemonset\"})",
     "legendFormat": "max spec hpa"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*$Deployment$Statefulset$Daemonset.*$\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*$Deployment$Statefulset$Daemonset.*$\"})",
     "legendFormat": "{{ persistentvolumeclaim }} | {{ kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\", namespace=~\"$namespace\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{id!=\"/\",pod_name=~\"^$Deployment$Statefulset$Daemonset.*$\", namespace=~\"$namespace\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  }
 ]
}