{
 "title": "MongoDB backups",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "name",
    "query": "label_values(mongodb_backups_scheduler_backup_total, name)"
   },
   {
    "name": "instance",
    "query": "label_values(mongodb_backups_scheduler_backup_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bucket snapshots",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(mongodb_backups_scheduler_bucket_snapshot_count{name=\"$name\"}) / count(mongodb_backups_scheduler_bucket_snapshot_count{name=\"$name\"})"
    }
   ]
  },
  {
   "title": "Last snapshot upload time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(mongodb_backups_scheduler_last_successful_snapshot{name=\"$name\", instance=~\"$instance\"})*1000"
    }
   ]
  },
  {
   "title": "Snapshot size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_backups_scheduler_snapshot_size{name=\"$name\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"mongodb-backups\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}