{
 "title": "ES dev",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(elasticsearch_cluster_health_status_code, name)"
   },
   {
    "name": "source",
    "query": "label_values(elasticsearch_cluster_health_status_code{name=\"$cluster\"}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status_code{name=\"$cluster\", status=\"red\", host=\"$source\"} == 1 or (elasticsearch_cluster_health_status_code{name=\"$cluster\", status=\"green\", host=\"$source\"} == 1)+4 or (elasticsearch_cluster_health_status_code{name=\"$cluster\", status=\"yellow\", host=\"$source\"} == 1)+22"
    }
   ]
  },
  {
   "title": "CPU Usage average",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(elasticsearch_clusterstats_nodes_process_cpu_percent{host=\"$source\", cluster_name=\"$cluster\"}[2m])"
    }
   ]
  },
  {
   "title": "JVM memory used Avg.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(elasticsearch_clusterstats_nodes_jvm_mem_heap_used_in_bytes{cluster_name=\"$cluster\", host=\"$source\"})  / sum(elasticsearch_clusterstats_nodes_jvm_mem_heap_max_in_bytes{cluster_name=\"$cluster\", host=\"$source\"}) * 100"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(elasticsearch_cluster_health_number_of_nodes{name=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{host=\"$source\"}"
    }
   ]
  },
  {
   "title": "Active primary shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{host=\"$source\", name=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{host=\"$source\", name=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collectors_young_collection_count{cluster_name=\"$cluster\", host=\"$source\"}[$interval])",
     "legendFormat": "{{ node_name }} young"
    },
    {
     "expr": "irate(elasticsearch_jvm_gc_collectors_old_collection_count{cluster_name=\"$cluster\", host=\"$source\"}[$interval])",
     "legendFormat": "{{ node_name }} old"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collectors_young_collection_time_in_millis{cluster_name=\"$cluster\", host=\"$source\"}[$interval])",
     "legendFormat": "{{ node_name }} young"
    },
    {
     "expr": "irate(elasticsearch_jvm_gc_collectors_old_collection_time_in_millis{cluster_name=\"$cluster\", host=\"$source\"}[$interval])",
     "legendFormat": "{{ node_name }} old"
    }
   ]
  }
 ]
}