{
 "title": "MongoDB",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(mongodb_cursor_pinned, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cache usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_wtcache_current_bytes{instance=\"$instance\"} / mongodb_wtcache_max_bytes_configured{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Cache usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_wtcache_current_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max cache",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_wtcache_max_bytes_configured{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "mongodb_connections_available{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "mongodb_connections_current{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_inserts_per_sec{instance=~\"$instance\"}",
     "legendFormat": "inserts"
    },
    {
     "expr": "mongodb_updates_per_sec{instance=~\"$instance\"}",
     "legendFormat": "updates"
    },
    {
     "expr": "mongodb_deletes_per_sec{instance=~\"$instance\"}",
     "legendFormat": "deletes"
    },
    {
     "expr": "mongodb_getmores_per_sec{instance=~\"$instance\"}",
     "legendFormat": "getmores"
    },
    {
     "expr": "mongodb_flushes_per_sec{instance=~\"$instance\"}",
     "legendFormat": "flushes"
    },
    {
     "expr": "mongodb_commands_per_sec{instance=~\"$instance\"}",
     "legendFormat": "commands"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_active_reads{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cache usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_wtcache_current_bytes{instance=~\"$instance\"}",
     "legendFormat": "current - {{ instance }}"
    },
    {
     "expr": "mongodb_wtcache_max_bytes_configured{instance=~\"$instance\"}",
     "legendFormat": "max - {{ instance }}"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_db_stats_storage_size{instance=~\"$instance\"}",
     "legendFormat": "{{ db_name }} {{ instance }}"
    }
   ]
  }
 ]
}