{
 "title": "RabbitMQ Metrics - Single",
 "description": "RabbitMQ metrics from a single Telegraf instance",
 "tags": [
  "rabbitmq",
  "prometheus",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(rabbitmq_node_running, instance)"
   },
   {
    "name": "node",
    "query": "label_values(rabbitmq_node_running{instance=\"$instance\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "$node",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_node_running{instance=\"$instance\", node=~\"$node\"}",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "Nodes Running",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_running{instance=\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Queued Messages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready{instance=\"$instance\", node=~\"$node\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(rabbitmq_queue_messages_unack{instance=\"$instance\", node=~\"$node\"})",
     "legendFormat": "Unacked"
    },
    {
     "expr": "sum(rabbitmq_queue_messages{instance=\"$instance\", node=~\"$node\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Global Counts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_overview_connections{instance=\"$instance\"}",
     "legendFormat": "Connections"
    },
    {
     "expr": "rabbitmq_overview_channels{instance=\"$instance\"}",
     "legendFormat": "Channels"
    },
    {
     "expr": "rabbitmq_overview_exchanges{instance=\"$instance\"}",
     "legendFormat": "Exchanges"
    },
    {
     "expr": "rabbitmq_overview_queues{instance=\"$instance\"}",
     "legendFormat": "Queues"
    },
    {
     "expr": "rabbitmq_overview_exchanges{instance=\"$instance\"}",
     "legendFormat": "Consumers"
    }
   ]
  },
  {
   "title": "Message Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rabbitmq_overview_messages_published{instance=\"$instance\"}[5m])",
     "legendFormat": "Publish"
    },
    {
     "expr": "rate(rabbitmq_overview_messages_acked{instance=\"$instance\"}[5m])",
     "legendFormat": "Acked"
    },
    {
     "expr": "rate(rabbitmq_overview_messages_delivered{instance=\"$instance\"}[5m])",
     "legendFormat": "Delivered"
    },
    {
     "expr": "rate(rabbitmq_overview_messages_delivered_get{instance=\"$instance\"}[5m])",
     "legendFormat": "Delivered_Get"
    },
    {
     "expr": "rate(rabbitmq_overview_messages_ready{instance=\"$instance\"}[5m])",
     "legendFormat": "Ready"
    },
    {
     "expr": "rate(rabbitmq_overview_messages_unacked{instance=\"$instance\"}[1m])",
     "legendFormat": "Unacked"
    }
   ]
  },
  {
   "title": "Top 10 Messages per Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rabbitmq_queue_messages{instance=\"$instance\", node=~\"$node\"})",
     "legendFormat": "{{node}}: {{queue}}"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_mem_limit{instance=\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{node}}:limit"
    },
    {
     "expr": "rabbitmq_node_mem_used{instance=\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{node}}:used"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_disk_free_limit{instance=\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{node}}:limit"
    },
    {
     "expr": "rabbitmq_node_disk_free{instance=\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{node}}:free"
    }
   ]
  }
 ]
}