{
 "title": "ChartMuseum",
 "tags": [
  "chartmuseum",
  "docker",
  "kubernetes",
  "helm",
  "internals"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(chartmuseum_chart_versions_served_total, namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(chartmuseum_chart_versions_served_total, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 3, "w": 5, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"$namespace\", pod=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "Total Charts Served",
   "type": "stat",
   "description": "Current number of charts served",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "chartmuseum_charts_served_total{pod=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Chart Versions Served",
   "type": "stat",
   "description": "Current number of chart versions served",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "chartmuseum_chart_versions_served_total{pod=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Resident Memory Usage",
   "type": "stat",
   "description": "Process Resident Memory Usage",
   "gridPos": { "h": 3, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{pod=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{pod=\"$instance\"}[5m]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{pod=\"$instance\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{pod=\"$instance\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{pod=\"$instance\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "HTTP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "How many HTTP requests processed, partitioned by status code and HTTP method.",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(chartmuseum_requests_total{pod=\"$instance\"}[5m])",
     "legendFormat": "{{ code }} {{ url }}"
    }
   ]
  },
  {
   "title": "HTTP Request Sizes",
   "type": "graph",
   "description": "The HTTP request sizes in bytes",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "chartmuseum_request_size_bytes{pod=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "0.5 "
    },
    {
     "expr": "chartmuseum_request_size_bytes{pod=\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "chartmuseum_request_size_bytes{pod=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "HTTP Request Latencies",
   "type": "graph",
   "description": "The HTTP request latencies in seconds",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "chartmuseum_request_duration_seconds{pod=\"$instance\", quantile=\"0.5\"} * 1000",
     "legendFormat": "0.5 "
    },
    {
     "expr": "chartmuseum_request_duration_seconds{pod=\"$instance\", quantile=\"0.9\"} * 1000",
     "legendFormat": "0.9"
    },
    {
     "expr": "chartmuseum_request_duration_seconds{pod=\"$instance\", quantile=\"0.99\"} * 1000",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "HTTP Response Sizes",
   "type": "graph",
   "description": "The HTTP response sizes in bytes",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "chartmuseum_response_size_bytes{pod=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "0.5 "
    },
    {
     "expr": "chartmuseum_response_size_bytes{pod=\"$instance\", quantile=\"0.9\"}",
     "legendFormat": "0.9"
    },
    {
     "expr": "chartmuseum_response_size_bytes{pod=\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "0.99"
    }
   ]
  }
 ]
}